version: "3"

services:
  app:
    build: .
    ports:
      - "5002:5002"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
