version: "3"

services:
  app:
    build: .
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    command: python -m flask run --host=0.0.0.0 --port=5002

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
